# PostgreSQL. Versions 9.3 and up are supported.
#
# Configure using DATABASE_URL environment variable or edit below.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reaping_frequency: 10

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://postgres:password@localhost:5432/duty_shuffle_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_TEST", "postgresql://postgres:password@localhost:5432/duty_shuffle_test") %>

production:
  <<: *default
  pool: <%= ENV.fetch("DATABASE_POOL", 15) %>
  url: <%= ENV.fetch("DATABASE_URL") { raise "Set DATABASE_URL for production" } %>
