default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/shakapacker
  webpack_compile_output: true
  webpacker_precompile: false
  compiler_strategy: digest

development:
  <<: *default
  compile: false

test:
  <<: *default
  compile: true

production:
  <<: *default
  compile: false
